# Common Features
USER_ID_FIELD: userID
ITEM_ID_FIELD: itemID
#RATING_FIELD: rating
TIME_FIELD: timestamp

filter_out_cod_start_users: True

inter_file_name: 'clothing.inter'

# name of features
vision_feature_file: 'image_feat.npy'
text_feature_file: 'text_feat.npy'
user_graph_dict_file: 'user_graph_dict.npy'


field_separator: "\t"

v_weight: 0.1
t_weight: 0.9  # 用于增强和去噪的权重
# modal_augmentation
modal_augment: False
augment_threshold: 3    # 对训练数据集中交互数小于5个的进行增强
modal_augment_ratio: 0.35   # 额外补充1个交互物品
# modal_denoise
modal_denoise: True
denoise_threshold: 15
modal_denoise_ratio: 0.1